apiVersion: apps/v1
kind: Deployment
metadata:
  name: techwave-backend
  namespace: default
  labels:
    app: techwave-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techwave-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: techwave-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: acrpracticafinalprod.azurecr.io/techwave-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techwave-frontend
  namespace: default
  labels:
    app: techwave-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techwave-frontend
  template:
    metadata:
      labels:
        app: techwave-frontend
    spec:
      containers:
      - name: frontend
        image: acrpracticafinalprod.azurecr.io/techwave-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"