apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: techwave-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

metadata:
  name: frontend-service
  namespace: techwave-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP






