apiVersion: v1
kind: Service
metadata:
  name: web-backend-svc
spec:
  selector:
    app: web
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
