version: "3.8"
services:
  backend:
    build: ../src/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  frontend:
    build: ../src/frontend
    ports:
      - "8080:8080"
