apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DATABASE_URL: "postgres://user:pass@db:5432/mydb"
  SECRET_KEY: "mi-secreto"
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"

