apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  set:
    loki.persistence.enabled: true
    loki.persistence.size: 10Gi
    promtail.enabled: true
    grafana.enabled: false
