name: Blue-Green Deployment

on:
  workflow_dispatch:
    inputs:
      color:
        description: 'blue or green'
        required: true
        default: 'green'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Switch ingress selector
        run: |
          echo "Switching traffic to ${{ github.event.inputs.color }}"
          
