name: Deploy to AKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3

    - name: Connect to AKS
      uses: azure/aks-set-context@v3
      with:
        resource-group: techwave-rg
        cluster-name: techwave-aks

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/app/
        kubectl rollout status deployment/frontend-deployment -n techwave-app
        kubectl rollout status deployment/backend-deployment -n techwave-app
